In [15]:
import pandas as pd 

df = pd.read_csv("../../data/clientes.csv", sep=";")
df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [16]:
def get_last_id(id):
    return id.split("-")[-1]

df["idCliente"] = df["idCliente"].apply(func=get_last_id)
df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [17]:
# Para conseguir transformar Salario em Float precisa primeiro deixar no formato de um float com uma funcao
exemplo = pd.DataFrame({
    "nome": ["teo", "lara", "nah", "bia", "mah", "lara", "mah", "mah"],
    "sobrenome" : ["calvo", "calvo", "ataide", "ataide", "silva", "silva", "silva", "silva"],
    "salario" : ["1 234,50"," 5312,00", "5221,13", "2345,41", "1 233,99", "6 643,53", "44 483", "6533,51"]
})
exemplo.head()

   nome sobrenome   salario
0   teo     calvo  1 234,50
1  lara     calvo   5312,00
2   nah    ataide   5221,13
3   bia    ataide   2345,41
4   mah     silva  1 233,99

In [18]:
def str_to_float(salario):
    salario = salario.replace(" ", "")
    salario = float(salario.replace(",", "."))
    return salario
    

exemplo["salario"] = exemplo["salario"].apply(func=str_to_float)
exemplo.dtypes

nome          object
sobrenome     object
salario      float64
dtype: object

In [25]:
def is_rich(x):
    return (x["salario"] > 5000 and x["sobrenome"] == "calvo")

exemplo["isRich"] = exemplo.apply(is_rich, axis= 1)
exemplo.head()

   nome sobrenome  salario  isRich
0   teo     calvo  1234.50   False
1  lara     calvo  5312.00    True
2   nah    ataide  5221.13   False
3   bia    ataide  2345.41   False
4   mah     silva  1233.99   False

(8, 3)