In [ ]:
import pandas as pd

df_clientes = pd.read_csv("../../data/clientes.csv", sep=";")
df_clientes

## Amostras

In [ ]:
# .head exibi as primeiras linhas ( a quantidade de linhas que voce passar como argumento )
df_clientes.head(5)

In [ ]:
# .tail exibi as ultimas linhas do dataframe ( pode passar a quantidade como argumento )
df_clientes.tail(10)

In [ ]:
# .sample mostra uma amostra aleatoria do df
df_clientes.sample(5)

## Estrutura do DataFrame

In [ ]:
# .shape mostra a dimensao  ( numero de linhas, numero colunas ) do DataFrame
df_clientes.shape

In [ ]:
# .columns mostra o nome de todas as colunas do DataFrame
df_clientes.columns

In [ ]:
# .index retorna os index de um Dataframe ou de um Series
df_clientes.index

In [ ]:
# .info retorna um resumo do dataframe
df_clientes.info(memory_usage="deep")

In [ ]:
# .dtypes retorna uma series que tem o tipo de dado de cada coluna
df_clientes.dtypes

## Colunas

In [ ]:
df = pd.read_csv("../../data/transacoes.csv", sep=";")
df.shape

In [ ]:
df.info(memory_usage="deep")

In [ ]:
df.dtypes

In [ ]:
# .rename muda o nome da coluna, tem qeu passar um dicionario onde a key é o nome atual e o value é o nome novo
# retorna um novo DataFrame, portanto é importantente utilizar inplace = True ou atribuir ao df
df.rename( columns={"QtdePontos" : "QuantidadePontos" }, inplace=True)
df

In [46]:
df

,IdTransacao,IdCliente,DtCriacao,QuantidadePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch
...,...,...,...,...,...
332331,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-24 12:22:26.313,1,twitch
332332,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,2024-08-16 13:09:42.576,1,twitch
332333,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100,2024-02-06 11:51:24.788,1,twitch
332334,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d,2026-04-14 12:03:03.720,1,twitch
332335,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943,2024-08-21 14:13:31.788,1,twitch

In [42]:
# Para visualizar colunas  so pode passar um elemento dentro das [],
# portanto se quiser visualizar mais de uma coluna e necessario passar um lista
# df['IdTransacao']
df[['IdTransacao', 'IdCliente']].head(5)
df[['IdTransacao', 'IdCliente']].sample(5)
df[['IdTransacao', 'IdCliente']].tail(5)

,IdTransacao,IdCliente
332331,ffff52de-13fb-4405-a797-fddb5b4a48c5,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3
332332,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,961622c3-3c29-4fa1-88d2-4f408d6d6ebb
332333,ffffc72e-d882-47f0-b933-cfd92c7e6621,2d3d2dce-d353-4961-ad39-46723efe2100
332334,ffffcd29-600c-4ae0-89b2-c62457eafc3f,c1a8d13d-cca9-4372-b195-9b0770d81a0d
332335,fffff928-9a18-4741-a516-3a92351d1d72,65662aff-44d6-4f06-b9d9-07445c6e5943

In [55]:
# Reordenar a ordem das colunas

lista_colunas = list(df.columns)
lista_colunas.sort()
df[lista_colunas]

,DescSistemaOrigem,DtCriacao,IdCliente,IdTransacao,QuantidadePontos
0,twitch,2025-09-17 12:28:41.864,24782f0b-4683-4f35-976a-ea21d6714ba6,0000520a-a4e5-4977-b360-17be62fa0f2b,1
1,twitch,2024-07-23 12:49:49.874,252a0923-3f79-45bb-b664-3040235c6c58,000060e8-aa76-4286-a8d7-f30e6fa47edd,1
2,twitch,2025-09-17 13:38:57.479,30f45a6d-ada5-4a17-8338-710e414eb6c6,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,1
3,twitch,2025-10-03 12:23:39.779,65662aff-44d6-4f06-b9d9-07445c6e5943,0000c010-a592-46f7-8b0b-6f841bee64ba,1
4,twitch,2024-02-20 13:21:45.613,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,0000dfbb-e14e-4ea7-a57f-60236869fffe,1
...,...,...,...,...,...
332331,twitch,2024-02-24 12:22:26.313,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,ffff52de-13fb-4405-a797-fddb5b4a48c5,1
332332,twitch,2024-08-16 13:09:42.576,961622c3-3c29-4fa1-88d2-4f408d6d6ebb,ffffb5ab-047e-43e4-bab3-ee2d19e9b7db,1
332333,twitch,2024-02-06 11:51:24.788,2d3d2dce-d353-4961-ad39-46723efe2100,ffffc72e-d882-47f0-b933-cfd92c7e6621,1
332334,twitch,2026-04-14 12:03:03.720,c1a8d13d-cca9-4372-b195-9b0770d81a0d,ffffcd29-600c-4ae0-89b2-c62457eafc3f,1
332335,twitch,2024-08-21 14:13:31.788,65662aff-44d6-4f06-b9d9-07445c6e5943,fffff928-9a18-4741-a516-3a92351d1d72,1