In [1]:
import pandas as pd

df = pd.read_csv("../../data/clientes.csv", sep=";")
df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [2]:
# Para converter o tipo de uma coluna é só usar astype
df["qtdePontos"].astype(float)
df.head()

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
3,0019bb9e-26d4-4ebf-8727-fc911ea28a92,0,0,0,0,0,2,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000
4,0028dda2-334f-40bb-9582-475fb6719471,1,1,1,0,0,1100,2025-10-29 02:08:18.367,2026-02-24 04:49:02.551

In [3]:
df["DtCriacao"] = pd.to_datetime(df["DtCriacao"])

In [4]:
# Exemplo de alterar o dado, usar um dicionario onde a key vai ser o valor antigo e o value vai ser o valor novo
# tem que usar atribuicao senao nao salva no df
df["DtCriacao"] = df["DtCriacao"].replace({"2025-11-13 12:03:56.114" : " 2024-02-01 09:00:00.000"})

In [ ]:
# Quando transfoma para date time da para acessar ano, mes, dia ...
df["DtCriacao"].dt.year
df["DtCriacao"].dt.day_of_week

0       3
1       3
2       3
3       3
4       2
       ..
5581    0
5582    5
5583    2
5584    2
5585    2
Name: DtCriacao, Length: 5586, dtype: int32