In [1]:
import pandas as pd

df = pd.read_csv("../../data/cartao.csv", sep= ";")
df

    idCliente  dtTransacao  vIVenda  qtParcelas
0           1   2025-01-01     3243           4
1           2   2025-01-26      423           2
2           1   2025-02-19      123           1
3           2   2025-01-29      543           2
4           3   2025-01-14      123           2
5           4   2025-01-16       65           1
6           3   2025-01-22      435           3
7           1   2025-01-30      234           1
8           2   2025-02-04     1237           5
9           3   2025-03-03      543           5
10          1   2025-02-22     9723           7
11          1   2025-03-17     1368           2

In [2]:
df.columns = df.columns.str.strip()
df["dtTransacao"] = pd.to_datetime(df["dtTransacao"].str.strip())
df.rename(columns= {"vIVenda" : "vlVenda"})

    idCliente dtTransacao  vlVenda  qtParcelas
0           1  2025-01-01     3243           4
1           2  2025-01-26      423           2
2           1  2025-02-19      123           1
3           2  2025-01-29      543           2
4           3  2025-01-14      123           2
5           4  2025-01-16       65           1
6           3  2025-01-22      435           3
7           1  2025-01-30      234           1
8           2  2025-02-04     1237           5
9           3  2025-03-03      543           5
10          1  2025-02-22     9723           7
11          1  2025-03-17     1368           2

In [3]:
df.head()

   idCliente dtTransacao  vIVenda  qtParcelas
0          1  2025-01-01     3243           4
1          2  2025-01-26      423           2
2          1  2025-02-19      123           1
3          2  2025-01-29      543           2
4          3  2025-01-14      123           2

In [4]:
df["vlParcela"] = df["vIVenda"] / df["qtParcelas"]

In [5]:
df["ordemParcela"] = df.apply(lambda row : [i for i in range(row["qtParcelas"])], axis=1) 
df_explode = df.explode(column = "ordemParcela")

In [6]:
df_explode.head(20)

   idCliente dtTransacao  vIVenda  qtParcelas  vlParcela ordemParcela
0          1  2025-01-01     3243           4     810.75            0
0          1  2025-01-01     3243           4     810.75            1
0          1  2025-01-01     3243           4     810.75            2
0          1  2025-01-01     3243           4     810.75            3
1          2  2025-01-26      423           2     211.50            0
1          2  2025-01-26      423           2     211.50            1
2          1  2025-02-19      123           1     123.00            0
3          2  2025-01-29      543           2     271.50            0
3          2  2025-01-29      543           2     271.50            1
4          3  2025-01-14      123           2      61.50            0
4          3  2025-01-14      123           2      61.50            1
5          4  2025-01-16       65           1      65.00            0
6          3  2025-01-22      435           3     145.00            0
6          3  2025-01-22      435           3     145.00            1
6          3  2025-01-22      435           3     145.00            2
7          1  2025-01-30      234           1     234.00            0
8          2  2025-02-04     1237           5     247.40            0
8          2  2025-02-04     1237           5     247.40            1
8          2  2025-02-04     1237           5     247.40            2
8          2  2025-02-04     1237           5     247.40            3