In [1]:
import pandas as pd

clientes = pd.read_csv("../../data/clientes.csv", sep=";")
clientes.head(3)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
0,000dc0f6-e4f2-4a42-b8cd-b586ed1c709a,0,1,0,0,0,2,2025-11-13 12:03:56.114,2025-12-13 11:45:37.364
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2,001749bd-37b5-4b1e-8111-f9fbba90f530,0,0,0,0,0,50,2024-02-01 00:00:00.000,2024-02-01 00:00:00.000

In [ ]:
# .sort_values ordena e retorna o series ordenada
clientes["qtdePontos"].sort_values()

509       -10
2792        0
2755        0
2757        0
2758        0
        ...
4916    17727
2137    18178
1       25086
4766    25979
965     30858
Name: qtdePontos, Length: 5586, dtype: int64

In [9]:
# Para ordenar e retornar um dataframe usa sort_values e by 
# Para ordernar de forma crescente usa ascending = True
# E ascending = False para decrescente
clientes.sort_values(by="qtdePontos", ascending=False).head(5)

# Posso fazer assim para pegar so uma coluna a partir de um Data Frame
# clientes.sort_values(by="qtdePontos", ascending=False).head(5)["IdCliente"]

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
965,2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1,1,1,0,0,0,30858,2025-03-07 12:59:11.756,2026-06-24 12:43:36.761
4766,d7f7eb75-4f0b-4d15-960d-8efe5ca7dd7e,0,0,0,0,0,25979,2025-03-07 12:36:50.254,2026-06-02 12:32:23.118
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2137,5ff083a7-e818-4367-bda5-a9cee8dec654,0,1,0,0,0,18178,2025-02-11 11:03:09.016,2026-06-23 11:55:00.453
4916,def56b88-a05b-465b-80ee-702831d3f535,0,1,0,0,0,17727,2025-02-12 11:38:11.917,2026-06-24 11:54:59.126

In [11]:
# Se quiser ordernar por mais de uma coluna 
clientes.sort_values(by=["qtdePontos", "flEmail"], ascending=[False, True]).head(5)

,idCliente,flEmail,flTwitch,flYouTube,flBlueSky,flInstagram,qtdePontos,DtCriacao,DtAtualizacao
965,2a9d4ba3-4c58-47f9-8dc4-6f9cb50be1b1,1,1,0,0,0,30858,2025-03-07 12:59:11.756,2026-06-24 12:43:36.761
4766,d7f7eb75-4f0b-4d15-960d-8efe5ca7dd7e,0,0,0,0,0,25979,2025-03-07 12:36:50.254,2026-06-02 12:32:23.118
1,000ff655-fa9f-4baa-a108-47f581ec52a1,0,0,0,0,0,25086,2024-02-01 00:00:00.000,2025-09-26 13:28:37.697
2137,5ff083a7-e818-4367-bda5-a9cee8dec654,0,1,0,0,0,18178,2025-02-11 11:03:09.016,2026-06-23 11:55:00.453
4916,def56b88-a05b-465b-80ee-702831d3f535,0,1,0,0,0,17727,2025-02-12 11:38:11.917,2026-06-24 11:54:59.126