In [1]:
import pandas as pd 

df = pd.read_csv("../../data/transacoes.csv", sep = ";" )
df.head(5)

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
0,0000520a-a4e5-4977-b360-17be62fa0f2b,24782f0b-4683-4f35-976a-ea21d6714ba6,2025-09-17 12:28:41.864,1,twitch
1,000060e8-aa76-4286-a8d7-f30e6fa47edd,252a0923-3f79-45bb-b664-3040235c6c58,2024-07-23 12:49:49.874,1,twitch
2,000095de-3daa-4cfb-a0ae-e7b2c8bc3c9b,30f45a6d-ada5-4a17-8338-710e414eb6c6,2025-09-17 13:38:57.479,1,twitch
3,0000c010-a592-46f7-8b0b-6f841bee64ba,65662aff-44d6-4f06-b9d9-07445c6e5943,2025-10-03 12:23:39.779,1,twitch
4,0000dfbb-e14e-4ea7-a57f-60236869fffe,5f8fcbe0-6014-43f8-8b83-38cf2f4887b3,2024-02-20 13:21:45.613,1,twitch

## Exemplo Simples

In [2]:
brinquedo = pd.DataFrame(
    { 
        "nome": ["Matheus", "José", "João"],
        "idade": [20, 30, 25],
        "uf" : ["pr", "sp", "sc"]
    }
)
brinquedo

      nome  idade  uf
0  Matheus     20  pr
1     José     30  sp
2     João     25  sc

In [3]:
# Filtro é um Series com true e false
filtro = brinquedo["idade"] < 28
# O que for True será mostrado 
brinquedo[filtro]

      nome  idade  uf
0  Matheus     20  pr
2     João     25  sc

## Exemplo com transações

In [4]:
filtro = df["QtdePontos"] >= 50
df[filtro]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
12,00028d36-4575-4d02-b2a0-bdae1bc83231,9d023e72-c799-40c0-907a-96e023a97959,2024-11-11 12:36:33.625,50,twitch
22,0003acb0-624a-4e65-bf95-426450b4434d,1b08989c-039d-4c82-879b-0f56159a1ebb,2025-11-25 12:13:19.266,50,twitch
29,00056eff-bd02-4394-bc44-2419bf8a9982,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-21 12:02:27.779,100,twitch
30,0005855d-2c33-4bfd-85fe-2c7ffaf73151,f5719706-915b-4bb1-b9be-c4acb3bd7837,2025-07-16 12:05:28.007,50,twitch
34,00068e23-5b1e-432a-83df-8a5d11e495a6,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,2025-01-09 12:29:28.501,50,twitch
...,...,...,...,...,...
332312,fffb4d1f-5197-470f-936e-f7289bc5c878,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-02-29 12:35:20.673,50,twitch
332315,fffba02b-d70c-4bfc-aa51-a4b66b442d53,ca35412d-b340-4e7d-a391-020ec6bb6517,2024-07-04 12:53:21.075,50,twitch
332319,fffd0631-ac87-4432-bf7d-b7200fda8f0c,1dd4b8bc-f909-42bf-9748-88decb919c94,2025-10-02 11:56:38.812,50,twitch
332320,fffd47aa-3e8f-4cd1-a125-342721ad4a45,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-08-12 12:46:44.489,100,twitch
332330,ffff495d-16ce-46ff-863d-6cc9fe2a6220,7107771a-0558-4aaa-a66e-570205a7f367,2026-04-24 12:20:46.720,50,twitch

In [5]:
# O & é utilizado para And
filtro = (df["QtdePontos"] >= 50) & (df["QtdePontos"] <= 100)
df[filtro]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
12,00028d36-4575-4d02-b2a0-bdae1bc83231,9d023e72-c799-40c0-907a-96e023a97959,2024-11-11 12:36:33.625,50,twitch
22,0003acb0-624a-4e65-bf95-426450b4434d,1b08989c-039d-4c82-879b-0f56159a1ebb,2025-11-25 12:13:19.266,50,twitch
29,00056eff-bd02-4394-bc44-2419bf8a9982,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-21 12:02:27.779,100,twitch
30,0005855d-2c33-4bfd-85fe-2c7ffaf73151,f5719706-915b-4bb1-b9be-c4acb3bd7837,2025-07-16 12:05:28.007,50,twitch
34,00068e23-5b1e-432a-83df-8a5d11e495a6,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,2025-01-09 12:29:28.501,50,twitch
...,...,...,...,...,...
332312,fffb4d1f-5197-470f-936e-f7289bc5c878,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-02-29 12:35:20.673,50,twitch
332315,fffba02b-d70c-4bfc-aa51-a4b66b442d53,ca35412d-b340-4e7d-a391-020ec6bb6517,2024-07-04 12:53:21.075,50,twitch
332319,fffd0631-ac87-4432-bf7d-b7200fda8f0c,1dd4b8bc-f909-42bf-9748-88decb919c94,2025-10-02 11:56:38.812,50,twitch
332320,fffd47aa-3e8f-4cd1-a125-342721ad4a45,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-08-12 12:46:44.489,100,twitch
332330,ffff495d-16ce-46ff-863d-6cc9fe2a6220,7107771a-0558-4aaa-a66e-570205a7f367,2026-04-24 12:20:46.720,50,twitch

In [6]:
# O | é utilizado para Or
filtro = (df["QtdePontos"] == 50) | (df["QtdePontos"] == 100)
df[filtro]

,IdTransacao,IdCliente,DtCriacao,QtdePontos,DescSistemaOrigem
12,00028d36-4575-4d02-b2a0-bdae1bc83231,9d023e72-c799-40c0-907a-96e023a97959,2024-11-11 12:36:33.625,50,twitch
22,0003acb0-624a-4e65-bf95-426450b4434d,1b08989c-039d-4c82-879b-0f56159a1ebb,2025-11-25 12:13:19.266,50,twitch
29,00056eff-bd02-4394-bc44-2419bf8a9982,820c0e06-c405-4979-8975-ecfa17abb0f9,2026-05-21 12:02:27.779,100,twitch
30,0005855d-2c33-4bfd-85fe-2c7ffaf73151,f5719706-915b-4bb1-b9be-c4acb3bd7837,2025-07-16 12:05:28.007,50,twitch
34,00068e23-5b1e-432a-83df-8a5d11e495a6,3f55b86f-dc21-4ac8-8e89-7c1535359eaf,2025-01-09 12:29:28.501,50,twitch
...,...,...,...,...,...
332312,fffb4d1f-5197-470f-936e-f7289bc5c878,9aba2685-7c0a-4d1f-8e22-0c47ca0af580,2024-02-29 12:35:20.673,50,twitch
332315,fffba02b-d70c-4bfc-aa51-a4b66b442d53,ca35412d-b340-4e7d-a391-020ec6bb6517,2024-07-04 12:53:21.075,50,twitch
332319,fffd0631-ac87-4432-bf7d-b7200fda8f0c,1dd4b8bc-f909-42bf-9748-88decb919c94,2025-10-02 11:56:38.812,50,twitch
332320,fffd47aa-3e8f-4cd1-a125-342721ad4a45,fcda54f6-b9e9-41cf-b255-0594d9947d1b,2024-08-12 12:46:44.489,100,twitch
332330,ffff495d-16ce-46ff-863d-6cc9fe2a6220,7107771a-0558-4aaa-a66e-570205a7f367,2026-04-24 12:20:46.720,50,twitch